### PR TITLE
Add npm version badge to the README

### LINKED ISSUE #111: Add npm version badge to the README.
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
  - [ ] **🙋 Claim this issue:** Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  - [ ] **📝 Update** 

  - [ ] **💾 Commit your changes**

 - [ ]  **🔀 Start a Pull Request.** There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

  - [ ] **🏁 Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

### PR DESCRIPTION
**Pull request by zlv2s**
Fix #111

* [ ] tests pass -- see README.md for how to run them
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by sidntrivedi012** [comment]
@zlv2s Hey, thanks for the PR. Can you please add a screenshot of the README in your branch where we can find the badge just to confirm. 

Thanks. 🎉

**Comment by zlv2s** [comment]
Snipaste_2019-07-24_12-05-06

 @sidntrivedi012 Sorry, screenshot attached, is that correct?

**Comment by sidntrivedi012** [comment]
LGTM. @jywarren PTAL. 

Thanks 💯

**Comment by jywarren** [comment]
Awesome. Thanks all!!!! Great work!

**Pull request merged**
