### PR TITLE
updated README for issue #145

### LINKED ISSUE #145: Add code of conduct badge to readme
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

Add the code of Conduct badge to readme.

In line 6 of readme , add the following

```
[![Code of Conduct](https://img.shields.io/badge/code-of%20conduct-green.svg)](https://publiclab.org/conduct)
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by Surajv311**
@SidharthBansal @ananyaarun  @cesswairimu  Could you please review my PR ?

* [X] tests pass -- see README.md for how to run them
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request are descriptively named
* [X] if possible, multiple commits squashed if they're smaller changes
* [X] reviewed/confirmed/tested by another contributor or maintainer

Fixes #145 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @Surajv311 thanks so much for opening this :tada: could you please add the issue link to the issue this pull request fixes on your pull request on this line "Fixes issue_link" this will help other contributors while reviewing your changes. It also helps in automatically closing the issue when the pull request is merged. Thanks

**Comment by Surajv311** [comment]
@cesswairimu . I have updated my PR. I hope it's done the right way. Could you please review ?

**Review by cesswairimu — APPROVED** [review]
Looks great :tada: Thanks @Surajv311  for working on this

**Comment by Surajv311** [comment]
@cesswairimu Thank you, mam. I also had a few doubts: After the checks have passed this would be merged now right? And can I be a member of publiclab organization on GitHub?

**Comment by cesswairimu** [comment]
Yeah it will be merged. Sure thing, one of the maintaners shall add you to the team.  And please Cess is fine. 😊. Thanks

**Comment by Surajv311** [comment]
@cesswairimu :) 👍.

**Comment by jywarren** [comment]
Thank you!!! Adding you now, too! 😄

**Pull request merged**
