### PR TITLE
ADD: Compile capture.js subfiles into one file

### LINKED ISSUE #151: Get capture.js subfiles compiling into a single file using Grunt
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

We have a file [capture.js](https://github.com/publiclab/spectral-workbench.js/blob/main/examples/capture/capture.js) which is now refactored here in this [PR](https://github.com/publiclab/spectral-workbench.js/pull/148). Here are the new imports in [index.html](https://github.com/publiclab/spectral-workbench.js/blob/5e54176b66b13b47d791253986371981d43b6bee/examples/capture/index.html#L26) file.
Now we actually want all the code in one file after getting compiled. What we can do is to install grunt and set up a compilation step that merges these files. That way the source files can be in the /src/ directory and the combined output file can be in /dist/.

This may sound like a lot but it's not too hard to set up. There is a good example in this library with documentation on how to use grunt to "build" or "compile" the source files.
https://github.com/publiclab/inline-markdown-editor#contributing

@jywarren @sidntrivedi012

### PR DESCRIPTION
**Pull request by VladimirMikulic**
As the title suggests, files #148 are now compiled in one file.

Resolves #151

@starkblaze01 @jywarren @ananyaarun could you take a look at this? Thanks.

### CODE REVIEW

**Comment by jywarren** [comment]
This looks awesome! Can you confirm that this works and share a gif? We don't have UI tests for this portion of the code yet... 

Thank you!

**Comment by VladimirMikulic** [comment]
@jywarren of course! Here it is:

ezgif com-video-to-gif (6)

**Comment by jywarren** [comment]
Awesome, and if you click "Begin" at the bottom, you see the "waterfall"
and graph? Thanks!

**Comment by VladimirMikulic** [comment]
@jywarren yes I do :smile: 

Screenshot_20200116_202647

**Comment by jywarren** [comment]
Great work!!!

**Comment by jywarren** [comment]
This is really great, because now we can start working on tests, and then refactoring a lot of this code, which badly needs it!

**Comment by VladimirMikulic** [comment]
I am glad that you like it!

**Pull request merged**
