### PR TITLE
Update to Use Temasys/AdapterJS for getUserMedia (brings iOS + Safari compatibility)

### LINKED ISSUE #87: Update getUserMedia WebRTC library for broader browser compatibility (+ iOS)
http://publiclab.org/spectral-workbench#Browsers lists:

> Spectral Workbench should work on Chrome (in Windows/Mac/Linux/Android, but not iOS), Firefox (Windows/Mac/Linux/Android), or Opera (Android). It may work on other browsers and we are working on expanding coverage; read more on this page:

Linking here; we should be able to support:

* [ ] Safari desktop
* [ ] iOS (soon, as we hear getUserMedia is now supported on iOS???)

Let's discuss/plan/collect information here!

This would also be possible to port back to https://github.com/publiclab/spectral-workbench/ once implemented here.

### PR DESCRIPTION
**Pull request by chukohsin**
## Description
Since [addyosmani/getUserMedia.js](https://github.com/addyosmani/getUserMedia.js/) is lack of maintenance. This replaces it with Temasys/AdapterJS, which provides polyfills and cross-browser helpers for WebRTC. It wraps around the native APIs in Chrome, Opera and Firefox and provides support for WebRTC in Internet Explorer and Safari on Mac and Windows through the available Temasys Browser Plugins.

fixes #87 (link added by @jywarren)

### Files Changed
- Add `examples/capture/getUserMedia.js`: this helper function includes the required initialization for AdapterJS and call `getUserMedia` with default constraints.
- `examples/capture/capture.js`: remove old options customized for `addyosmani/getUserMedia.js`. Move success callback to `getUserMedia.js` helper function.
- `examples/capture/getRow.js`: Remove conditional statements customized for `addyosmani/getUserMedia.js` flash fallback. 
- `package.json`: remove `"getusermedia-js": "~1.0.0"`
- `examples/capture/index.html`: add AdapterJS

### Notes
This has been tested on Chrome, Firefox and Safari. 

---
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

- [x] tests pass -- see README.md for how to run them
- [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
- [x] pull request are descriptively named
- [ ] if possible, multiple commits squashed if they're smaller changes
- [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Review by jywarren — APPROVED** [review]
This looks fantastic. Tested on iOS Safari with version info:

```
phone()
iPhone
tablet()
-
mobile()
iPhone
os()
iOS
userAgent()
Safari
mobileGrade()
A
smaller side
375
_version
1.4.4 2019-09-21
is("iPhone")
true
is("iOS")
true
is("Safari")
true
is("WebKit")
true
versionStr("Mobile")
"15E148"
version("Mobile")
15.148
versionStr("Version")
"13.1.2"
version("Version")
13.12
versionStr("iPhone")
"13_7"
version("iPhone")
13.7
versionStr("Opera")
"13.1.2"
version("Opera")
13.12
versionStr("Opera Mobi")
"13.1.2"
version("Opera Mobi")
13.12
versionStr("Safari")
"13.1.2"
version("Safari")
13.12
versionStr("Webkit")
"605.1.15"
version("Webkit")
605.115
versionStr("iOS")
"13_7"
version("iOS")
13.7
```

I do note we can't flip the camera, but once we merge this perhaps we can address that in a follow-up PR or in #173. Thank you so much!

**Comment by Forchapeatl** [comment]
Hello @jywarren  I have gone through all the live demo episodes of [https://plugin.temasys.com.sg/demo/](https://plugin.temasys.com.sg/demo/) on Safari. It seems only the first frame gets captured. Please could you test it at your end. 
@chukohsin  please can you help me with temasys resources/documents?

**Comment by jywarren** [comment]
Ah, so it seems that this may be a temasys systemic issue?

**Comment by Forchapeatl** [comment]
@jywarren  , **sorry for the late response**. 

Temasys works fine on both `Fire Fox` and `Chrome`. I believe Safari no longer supports `Temasys`.
image
from [https://support.temasys.com.sg/support/solutions/articles/12000049210-end-of-support-for-temasys-webrtc-plugin-on-safari-12-and-onwards](https://support.temasys.com.sg/support/solutions/articles/12000049210-end-of-support-for-temasys-webrtc-plugin-on-safari-12-and-onwards) .

**Comment by Forchapeatl** [comment]
I have contacted the technical team in regards to this single frame limitation

**Comment by jywarren** [comment]
Oh whoa! Ok, so, perhaps we need to either look at another compatibility
library or try directly using the getUserMedia API. The API has stabilized
in recent years so a compatibility library may not be as necessary anymore.

**Pull request merged**
